### ISSUE TITLE
August 2021 To-do: Preparation to Commission Little Dave rig

### ISSUE THREAD

**Issue by john-judge** [john-judge/PhotoLib#10]
Continued from https://github.com/john-judge/PhotoLib/issues/1

## 8/14/21 - 8/17/21
- [x] ~~#13~~ This turned out to be 1) too slow to apply baseline correction to all 40,000+ traces, and 2) interfered with acquisition and was too difficult to sync between threads to prevent interference. Not worth doing, and not possible unless we find a MUCH faster way to baseline correct the whole array.
- [x] Apply data inversing, baseline correction, and t-filter to data BEFORE computing the display frame. Currently we do not do this for performance reasons -- instead we only apply these when traces are viewed. Full processing (previous point) will make this possible.
- [x] Save/Load preference files: see https://github.com/john-judge/PhotoLib/issues/11
- [x] Trace time cropping for Data time window, to apply to all traces, keeping absolute frame number consistent and correct. This should be thoroughly tested. The new Trace class enforces this consistency on a display trace-by-trace basis -- next enforce this cropping window to entire Data class. **To discuss with Meyer** -- implemented with a crop_window in metadata that applies to the temporal axis.
- [x] Load file when slice, loc, rec flipped through. This is related to the next point.
- [x] Memory requirement reduction / speed up file management with `np.load` in mmap_mode ([refer to this](https://stackoverflow.com/questions/42727412/efficient-way-to-partially-read-large-numpy-file) and [especially this](https://numpy.org/doc/stable/reference/generated/numpy.memmap.html#numpy.memmap)).  This allows us to never need more than one trial in memory at a time, and write back only parts of a file at a time. The file [can even be resized](https://numpy.org/doc/stable/reference/generated/numpy.memmap.resize.html), but care needs to be taken to avoid overwriting data.
- [x] Don't save all RLI frames -- just calculate avg high minus avg low, and keep only low, high, and max.

##  8/18/21
- [x] Fix acqui/hardware code to work with new database implementation
- [x] Test acqui/hardware code to work with new database implementation
- [x] Average trials. (Often we need to average 20 trials) when Trial Number field set to ALL
- [x] Export Saved Traces to file -- Tab-separated value (.tsv) to work with Origin
- [x] Save/Load preferences from drop-down menu
- [x] Export Saved Frame to file -- Tab-separated value to work with Origin
- [x] Savefig: export display frame (see Array tab "Save Background Data") or traces (Save Right/Left Window) or other plots (ROI clustering) to PNG
- [x] Background display value in FrameViewer (implementing here in `get_display_frame` will automatically carry over to exported frames.

**Comment by john-judge** [comment]
![modules](https://user-images.githubusercontent.com/40705003/129463257-d7634aa2-1a79-4424-a6c0-4baa31c8eda4.png)

**Comment by john-judge** [comment]
## Next
### To-do before ready for full recording test run:
- [ ] Record Time Course (LTP) -- show display value over time


### Medium priority
- [ ] Measure window (under PhotoZ in DSP tab > Main): the window in which analysis is done (MaxAmp/SD, etc). (Will offer only 1 generic window, but some workflows require multiple Measure Windows (e.g. ROI Identification requires a Stim and Pre-Stim window)
- [ ] Artifact exclusion: Set number of points to skip due to artifacts (by increasing `Metadata.crop_window[0]` -> this keeps frame index consistent with absolute number) -- seems somewhat necessary depending on observed Little Dave behavior so far.
- [ ] Overlay all traces on the display frame when binning is high


### Lower priority to-do:
- [ ] Distance conversion (from pixel distance -> actual distance in microns) --  calculation dependent on lens magnification, and may want to compare a few conversions empirically
- [ ] Easier window selection: should launch trace viewer separately, and have an accept to pull in the selected trace. OR plots the current time window in plot, and allows user to click to modify. This will be used for Measure Window, Baseline Skip Window, and windows needed for ROI -- inherit from a generic TimeWindow base class
- [ ] Load image from file and display as translucent overlay, and adjust scale/x-y location
- [ ] ROI Identification workflow (Kate)
- [ ] Save analysis metadata / processed data
- [ ] Export to Movie
- [ ] Replace built-in Toolbar with better-performing zoom/pan for TraceViewer
- [ ] Slope
- [ ] Simulation
- [ ] Ideas for refactors to clean up code: Viewer base class, 
- [ ] Color: toggle grayscale, viridis, and jet colormaps
- [ ] Baseline Clamp-at-Point -- clamp at first point is occasionally used


### Not necessary
-  Latency values: %Amp Latency, Max Amp Latency, EPSP Latency
-  FP trace inversing
-  Acquire images while in live feed mode (Sarwagya's idea)
-  Compressed .npz memmap files to save disk space?


### Documentation To-do

- [ ] Architecture technical manual (in README on github)
- [ ] Tutorial for user (YouTube video?)
- [ ] Link Little Dave sign-up calendar from button in the app
- [ ] Link these from buttons in the app

**Comment by john-judge** [comment]
### High priority
- [ ] Analysis-only mode: In analysis-only mode, we do not create any new files automatically. This mode is automatically set if the DLL is not found. In this mode, the hardware control buttons are inactive. There will be a checkbox to manually toggle this mode on or off. Note: this can probably replace the auto-save mode, i.e. auto-save OFF = analysis-only ON.

### Medium priority
- [ ] Put all traces on a single plot, with no y-axis, so we can see more traces. Get rid of toolbar in the process and implement alternative method for zoom, pan.
- [ ] Refactor GUI to use `field_bindings.py` to automatically keep fields up-to-date with database
- [ ] Export each region pixel indices to a TSV titled "Region #.tsv" when exporting traces.
- [ ] Overlay all traces on the display frame when binning is high
- [ ] Record Time Course (LTP) -- show display value over time
- [ ] Latency values: %Amp Latency, Max Amp Latency, EPSP Latency, HW Latency. E.g. measure time from stimulation to rising edge.
- [ ] Velocity workflow

### Lower priority to-do:
- [ ] Distance conversion (from pixel distance -> actual distance in microns) --  calculation dependent on lens magnification, and may want to compare a few conversions empirically
- [ ] Pixel-by-pixel Frequency Decomposition for oscillatory behavior analysis
- [ ] Easier window selection: should launch trace viewer separately, and have an accept to pull in the selected trace. OR plots the current time window in plot, and allows user to click to modify. This will be used for Measure Window, Baseline Skip Window, and windows needed for ROI -- inherit from a generic TimeWindow base class
- [ ] Load image from file and display as translucent overlay, and adjust scale/x-y location
- [ ] ROI Identification workflow (Kate)
- [ ] Save analysis metadata / processed data
- [ ] Export to Movie
- [ ] Slope
- [ ] Simulation
- [ ] Ideas for refactors to clean up code: Viewer base class, 
- [ ] Color: toggle grayscale, and jet colormaps
- [ ] Baseline Clamp-at-Point -- clamp at first point is occasionally used


### Not necessary
-  FP trace inversing
-  Acquire images while in live feed mode (Sarwagya's idea)
-  Compressed .npz memmap files to save disk space?


### Documentation To-do

- [ ] Architecture technical manual (in README on github)
- [ ] Tutorial for user (YouTube video?)
- [ ] Link Little Dave sign-up calendar from button in the app
- [ ] Link these from buttons in the app
